[pytest]
addopts =
    --base-url=https://www.saucedemo.com
    --browser=chromium
    --alluredir=allure-results
    -n auto
    --dist=loadfile

testpaths = tests

markers =
    smoke
    e2e
    ddt